### ISSUE TITLE
Command-line script for MOC generation / filtering / etc

### ISSUE THREAD

**Issue by tboch** [cds-astro/mocpy#10]
It would be nice to have some command-line scripts for some common operations as:

- MOC generation from a list of positions
- catalogue filtering by a MOC
- MOC operations (union/intersection)

**Comment by tboch** [comment]
comment: the scripts structure should be similar to what is done in astropy, see for instance http://docs.astropy.org/en/stable/io/fits/usage/scripts.html

**Comment by fxpineau** [comment]
@tboch 
I added [moc-cli](https://github.com/cds-astro/cds-moc-rust/tree/main/crates/cli) in [pypi](https://pypi.org/project/moc-cli) and put the link in the MOCPy REAMDE.rst file.
