### ISSUE TITLE
Improve from_fits_images when working with MEF

### ISSUE THREAD

**Issue by tboch** [cds-astro/mocpy#110]
I would like to easily create a MOC from a list of multi-extension FITS (each HDU being a FITS image).

I suggest that *hdu_index* could be either:

- a scalar (as already supported)
- a list of HDUs, eg *hdu_index = [1, 2, 3, 4]*
- a magic value *'all'* which would iterate over all the HDUs, silently ignoring the HDU not being images

**Comment by ManonMarchand** [comment]
Would you have a file to help testing this ?
