### ISSUE TITLE
Create a MOC from STC-S string

### ISSUE THREAD

**Issue by tboch** [cds-astro/mocpy#111]
It would be nice to be able to create directly a MOC from [STC-S string](https://ivoa.net/documents/STC-S/) .

We do not need to support all STC-S nuances at first, starting with single polygon support would be a great start.

**Comment by ManonMarchand** [comment]
No need for a new issue FX ;)

**Comment by fxpineau** [comment]
And [here](https://www.ivoa.net/documents/STC-S/20130917/index.html) the IVOA note with the [pdf](https://www.ivoa.net/documents/STC-S/20130917/WD-STC-S-1.0-20130917.pdf) version.

**Comment by fxpineau** [comment]
A Rust STC-S parser has been developed [here](https://github.com/cds-astro/cds-stc-rust/) and the STC-S to MOC features have been added to MOC Lib Rust -- in [this commit](https://github.com/cds-astro/cds-moc-rust/commit/3442876a5658158f95032263163b36463526552f) -- , in [MOCCli](https://github.com/cds-astro/cds-moc-rust/blob/main/crates/cli/README.md), in [MOCWasm](https://github.com/cds-astro/cds-moc-rust/blob/main/crates/wasm/README.md) and in [this](https://github.com/cds-astro/mocpy/commit/0b3d223390ab3224e9e8a5890bf167d855ecc109) and [this](https://github.com/cds-astro/mocpy/commit/f48054260467aee79a3e519b35fb462928c9d23b) MOCPy commits.

The features still has to be tested more thoroughly.

I close this issue, but feel free to re-open it if bugs are found.
