### ISSUE TITLE
CI fails for external contributors

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/mocpy#113]
I'm in holidays so won't do it before one week, but CI is broken so we can't merge #112 yet.

**Comment by fxpineau** [comment]
The CI seems to be fixed, I let you re-open if it is not the case.

**Comment by ManonMarchand** [comment]
It was a super strange bug, but seems transitory. Linking an open issue for documentation purposes in case it happens again: https://github.com/actions/checkout/issues/1326

**Comment by ManonMarchand** [comment]
It happened again, and for an other new contributor

**Comment by ManonMarchand** [comment]
Could it be because of 

```yml
with:
  ref: ${{ github.head_ref }}
```

in our actions setup?

**Comment by haooliveira84** [comment]
Same here
