### ISSUE TITLE
Add travis-ci?

### ISSUE THREAD

**Issue by cdeil** [cds-astro/mocpy#12]
How about setting up travis-ci for this repo, with a Python 2.7 and 3.5 build?

If you want I can send a PR with a `.travis.yml` file, but activating travis-ci needs to be done by an owner first (it's free and quick).

**Comment by bmatthieu3** [comment]
Yes you can send a PR with the yaml.
We plan to activate travis-ci with @tboch  .

thanks!

**Comment by bmatthieu3** [comment]
We have just activated travis-ci so you can send a PR with the yml file.
Thank you again !
