### ISSUE TITLE
Parallelized (on the Rust side) MOC generation

### ISSUE THREAD

**Issue by mcoughlin** [cds-astro/mocpy#137]
First of all, thank you for all the work to make this an excellent and useful package.

One very common operation is to replicate the same region (be it a square, circle, or some kind of polygon region) in a tiling pattern over the sky. For now, per the docs, I can do something like:

        center = SkyCoord(ra_pointing, dec_pointing, unit="deg", frame="icrs")
        region = regions.RectangleSkyRegion(
            center, config_struct["FOV"] * u.deg, config_struct["FOV"] * u.deg
        )
        moc = MOC.from_astropy_regions(region, max_depth=10)

To create my region, looping over the various RAs and DECs. However, this is a bit slow. I assume faster would be something on the MOC side where the from_box and from_circle and similar you could pass an array of RAs and DECs and a box size and radius and get back a list of MOCs. This would assuredly save time as sometimes you want to generate 100,000 of these MOCs in one go, depending on the instrument FOV.

Is this feasible?

**Comment by ManonMarchand** [comment]
It's feasible (maybe not this week though).

Did you benchmark `from_polygons` for your use case? Because we did not. What's the gain like? For example between these:

- call `from_polygon` in a python loop
- use `from_polygons` without multithreading (the loop is on the rust side)
- use `from_polygons` with multithreading

**Comment by mcoughlin** [comment]
@ManonMarchand To try this, I am moving this code:

    moc = None                                                    
    for subfield_id, coords in enumerate(quadrant_coords_icrs[0]):           
        if subfield_ids is not None:           
            if subfield_id not in subfield_ids:
                continue

        if moc is None:
            moc = MOC.from_polygon_skycoord(coords)
        else:
            moc = moc + MOC.from_polygon_skycoord(coords)

to:

    polygons = [] 
    for subfield_id, coords in enumerate(quadrant_coords_icrs[0]):
        if subfield_ids is not None:
            if subfield_id not in subfield_ids:
                continue
        polygons.append(SkyCoord(coords.ra, coords.dec)) 
    mocs = MOC.from_polygons(polygons)   

But how do I do the union in the fastest way possible?

**Comment by ManonMarchand** [comment]
You want the union of all the mocs in the list? That'd be `sum(mocs)`

**Comment by mcoughlin** [comment]
@ManonMarchand 

This currently seems slow since I have to convert to a SkyCoord polygon rather than use the RAs/Decs directly:

        lon_lat_list = [
            f(x)
            for x in list_vertices
            for f in (lambda x: x.icrs.ra.deg, lambda x: x.icrs.dec.deg)
        ]
        indices = mocpy.from_polygons(lon_lat_list, np.uint8(max_depth), n_threads)
        return [cls(index) for index in indices]

Perhaps it is possible to use the lon_lat_list (or RA/decs) directly?

**Comment by ManonMarchand** [comment]
Yes, we could make two versions like there is for `from_polygon` and `from_polygon_skycoord`.
You can try directly for now to see if it impacts a lot

```python
from mocpy import mocpy # this is the rust API
mocpy.from_polygons(lon_lat_list, np.uint8(10), None)
```

The only thing is that now the user needs to provide the coordinates in degrees and icrs, otherwise the MOC will be wrong without raising an issue.

**Comment by mcoughlin** [comment]
@ManonMarchand Happy to report I see speed-up about linear in number of cores (I just tried a couple of examples quick) when specifying n_threads > 0.

**Comment by mcoughlin** [comment]
@ManonMarchand Looking forward to the same thing for the box and the circle :)

**Comment by fxpineau** [comment]
@mcoughlin Just to be sure, you have ~100,000 FOV, each one is a polygon (how many vertices per polygon?). Then you want one MOC per FOV or you want the union of all ~100,000 MOCs?

**Comment by mcoughlin** [comment]
For this purpose, I will want one MOC per FOV. I have been using order 10 generally. Each FOV is represented by either a square (ZTF) or circle (DECam). I tested out your polygon version on the quadrant version of the FOVs where ZTF has 64 square quadrants representing the region.

**Comment by mcoughlin** [comment]
@fxpineau The key is that the size of the box or the circle is the same across all FOVs, just the RA/Dec center that is changing.

**Comment by fxpineau** [comment]
@mcoughlin and what about the box position angle? I guess it changes, right?

**Comment by mcoughlin** [comment]
@fxpineau No for ZTF there is no rotation.

**Comment by mcoughlin** [comment]
Thanks @fxpineau @ManonMarchand for all your work on this. Is there a branch on the python side to try these out?

**Comment by ManonMarchand** [comment]
Hi! Not yet, but I might find some time at the end of the week to look at it

**Comment by mcoughlin** [comment]
Thanks @ManonMarchand! All the help is appreciated.

**Comment by ManonMarchand** [comment]
Hi ! The features are merged in `master` can you tell us if it works like you wanted?

**Comment by mcoughlin** [comment]
@ManonMarchand Wow, it's blazing fast. Thanks so much @ManonMarchand!

**Comment by mcoughlin** [comment]
@ManonMarchand as always, if you wouldn't mind doing a release at some point, would help with our production instance.

**Comment by ManonMarchand** [comment]
We have tiny issues in automatic WCS and CI that we'd like to fix before a release, but it's in our radars :slightly_smiling_face:

**Comment by ManonMarchand** [comment]
The new version is out :slightly_smiling_face:

**Comment by mcoughlin** [comment]
Thanks @ManonMarchand. Appreciated as always.

**Comment by mcoughlin** [comment]
@ManonMarchand Also doing the conda release would be appreciated, once you have time.

**Comment by fxpineau** [comment]
It is so far broken because of numpy2.0, see [here](https://github.com/conda-forge/mocpy-feedstock/pull/17/checks?check_run_id=26727224507). Probably have to pin the version in the conda recipe...

**Comment by ManonMarchand** [comment]
Arg. Opening an issue for numpy2.0
