### ISSUE TITLE
Multiple Subplotting Issue/help

### ISSUE THREAD

**Issue by duytnguyendtn** [cds-astro/mocpy#139]
Hello mocpy maintainers!

I was wondering if I could get some help on plotting mocs in matplot lib. I was following the example on [astropy table plotting](https://cds-astro.github.io/mocpy/_collections/notebooks/from_astropy_table.html) and was trying to extend it. When a colleague tried to extend the figure to include multiple mocs, the field of view got cut off and started looking weirdly. I can reproduce the issue by just taking the example and looping it a few times:

<details>

<summary> Looped moc code </summary>

```
import matplotlib.pyplot as plt
from astropy import units as u
from astropy.coordinates import Angle, SkyCoord
from astropy.visualization.wcsaxes.frame import EllipticalFrame
from astroquery.vizier import Vizier
from mocpy import MOC, WCS

viz = Vizier(columns=["*", "_RAJ2000", "_DEJ2000"])
viz.ROW_LIMIT = -1  # sets the limit to infinity
table = viz.get_catalogs("I/293/npm2cros")[0]

moc = MOC.from_lonlat(
    table["_RAJ2000"].T * u.deg,
    table["_DEJ2000"].T * u.deg,
    max_norder=6,
)

fig = plt.figure(dpi=400, figsize=(10,20))
loop_range = range(1,4)
for index in loop_range:
    with WCS(
        fig,
        fov=160 * u.deg,
        center=SkyCoord(0, 0, unit="deg", frame="galactic"),
        coordsys="galactic",
        rotation=Angle(0, u.degree),
        projection="AIT",
    ) as wcs:
        ax = fig.add_subplot(max(loop_range), 1, index, projection=wcs, frame_class=EllipticalFrame)

        moc.fill(
            ax=ax,
            wcs=wcs,
            edgecolor="teal",
            facecolor="orange",
            linewidth=1.0,
            fill=True,
            alpha=0.8,
        )
        moc.border(ax=ax, wcs=wcs, color="k")

    ax.grid(True)

plt.tight_layout()
```

![image](https://github.com/cds-astro/mocpy/assets/25206008/c592aae7-2a14-42d5-bd94-fe88993cbeff)

</details>

If I adjust the `figsize` to be square, it fills the entire frame, but still cuts off the data:

<details>

<summary> figsize=(20,20) </summary>

![image](https://github.com/cds-astro/mocpy/assets/25206008/4ef2641c-3bc3-4fe4-a28d-64a6097e524b)

</details>

I can't tell if the WCS projection is warping it for some reason, or if I'm doing something wrong with the plotting. Help would be greatly appreciated!

Thanks,
Duy

**Comment by ManonMarchand** [comment]
I would advise to use your own WCS ( that you can do with astropy) for this use case, as our wrapper only takes one float for the field of view. It's as if it was assumed that the figure should be a square.

I'm not really sure of the reasoning behind this choice that we made.

**Comment by ManonMarchand** [comment]
Marking this as a bug while investigating. 
However, with a proper WCS from astropy rather than our automatically generated one, you should be able to get subplots without issues.

**Comment by ManonMarchand** [comment]
I'll close the issue for now, but don't hesitate to re-open or to write a new one if you still have issues with plotting MOCs
