### ISSUE TITLE
PyPI wheels for manylinux2014 x86_64

### ISSUE THREAD

**Issue by hombit** [cds-astro/mocpy#141]
Currently, PyPI releases have binary wheels for manylinux2_17 for aarch64 and i686, but not for x86_64, which is built for manylinux2_28. Unfortunately, many legacy environments still run with glibc <2.28. I kindly ask that you provide wheels for manylinux2014/manylinux2_17

**Comment by fxpineau** [comment]
I do not remember exactly why we dropped manylinux2014 (@ManonMarchand , do you remember?): a CI issue/warning or something similar...
I just generated and uploaded `manylinux_2_17_x86_64.manylinux2014_x86_64` and `musllinux_1_2_x86_64` wheels from my desktop.

**Comment by hombit** [comment]
Thank you!

**Comment by ManonMarchand** [comment]
Opening again to remind myself to add it in the CI before the next release
