### ISSUE TITLE
Max, min, median, average Distance in a region

### ISSUE THREAD

**Issue by santier14** [cds-astro/mocpy#144]
Hello simiar to probabilities_in_multiordermap(moc,skymap), is it possible to have a function distance_in_multiordermap(moc2,skymap) for GW alerts, because the map is 3D with a distance per pixel in it. Thanks

**Comment by fxpineau** [comment]
When computing the min/max, if a cell of the multi-order map is partially covered by a MOC, would you ignore or take into account the value (the distance in your case) it contains? For the mean/median, would you consider each value with a weight of 1 or would you like to apply a weight which depends on the surface area of the part of multi-order map cells covered by the MOC?
Also, we just made a new MOCPy release, would you have other requirements?

**Comment by MPillas** [comment]
Hello @fxpineau, I am working with @santier14. If possible, I would consider the value if it is partially covered. For the weights, I think the best in our case would be to return both the associated distance and the weight that depends on the surface area of the part of multi-order map cells covered by the MOC. Is that possible? 
Thanks!

**Comment by fxpineau** [comment]
Hi @MPillas,

If I understand correctly, from an API point-of-view, you would like a method `MOC.multiordermap_values_and_weigths(self, multiordermap: Table, column: str)`
returning a numpy table made of 2 columns:
* the values of `column` covered by the MOC
* the weights assoicated with those values (weight = surface area of the part of the multi-order map cell covered by the MOC)

Then, you will be able to compute the min/max/mean/weithed mean/median/... on your side.
Does that sound good?

**Comment by MPillas** [comment]
That would be great, thanks !

**Comment by fxpineau** [comment]
First implementation (to be tested) made in the Rust part of the code:
* in moc-lib-rust, see [this commit](https://github.com/cds-astro/cds-moc-rust/commit/7619b57601535603a7481f29b56b2e0486285d31)
* in mocpy, see [this commit](https://github.com/cds-astro/mocpy/commit/319396b0b14a9c189406351258fc0f0864ca5dd2) on the [pyo3v21 branch](https://github.com/cds-astro/mocpy/commits/pyo3v21/)

**Comment by MPillas** [comment]
@fxpineau Does this commit have been merged so we can use it?

**Comment by ManonMarchand** [comment]
Hello, only the rust part is merged for now. We'll do the python port soon

**Comment by fxpineau** [comment]
@ManonMarchand 
I just added a method `multiorder_filter_mask_in_smoc` on the Rust part of the code, see [this commit](https://github.com/cds-astro/mocpy/commit/bb79d0ecab57b840d30777ca7c554b768bd4df1e).

**Comment by ManonMarchand** [comment]
@MPillas , @santier14 : can you can try the new method (`MOC.mask_uniq`) in the branch https://github.com/cds-astro/mocpy/tree/pyo3v21 and tell us if it works for you?

There are two options for the cells that are not entirely in the MOC:
- if `fully_covered_only` is true, you get a mask that only keeps uniq cells that are fully in the MOC
- otherwise, any uniq cell that intersects the MOC is also included

**Comment by ManonMarchand** [comment]
Implemented in https://github.com/cds-astro/mocpy/pull/151
It will be in the next release
