### ISSUE TITLE
Support of numpy 2.0

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/mocpy#145]
We need it as it looks like it's making the conda release fail (no idea why, investigation needed)

**Comment by ManonMarchand** [comment]
Relevant PR: [Add support for Numpy 2.x PyO3/rust-numpy#429](https://github.com/PyO3/rust-numpy/pull/429)

**Comment by lpsinger** [comment]
Update: someone else has taken over that PR as https://github.com/PyO3/rust-numpy/pull/442.
