### ISSUE TITLE
`from_healpix_cells` no longer allows HEALPix cells with index 0

### ISSUE THREAD

**Issue by smcguire-cmu** [cds-astro/mocpy#157]
In the latest release we noticed that creating a MOC with the `from_healpix_cells` method removes pixels with index 0, raising the warning `The list of indices contain negative values`. I believe this is a bug introduced with #149.

Reproducing code:
```
MOC.from_healpix_cells(np.array([0]), np.array([0]), 0)
```

mocpy Version: '0.16.0'

**Comment by ManonMarchand** [comment]
Ouch, that a very nasty one. Releasing a bugfix version as soon as #158 is merged and the tests pass. Thanks a lot for reporting.

**Comment by ManonMarchand** [comment]
version 0.16.1 is out, thanks again for the bug report!!

**Comment by smcguire-cmu** [comment]
Thanks for the quick fix!
