### ISSUE TITLE
Angle object for inputs in MOC.add_position?

### ISSUE THREAD

**Issue by cdeil** [cds-astro/mocpy#16]
In https://github.com/cds-astro/mocpy/pull/15/files#diff-a40381ce2439dfbb7713590bad6e5b75R53 I noticed that  in `MOC.add_position`  the docstring says that `Angle` objects are the input for `ra` and `dec`, but then the current implementation (both before and after this change) assumes that it's floats or float arrays in deg.

Suggest to change to quantity inputs like in the `astropy_healpix` API.
Requires adapting callers, and maybe even increate test coverage a bit before changing.

**Comment by bmatthieu3** [comment]
I close this one because ``from_lonlat`` now takes astropy quantities. In the future it will be better to take astropy Longitude and Latitude directly.  This refers to cds-astro/cds-healpix-python#2
