### ISSUE TITLE
MOC.from_astropy_regions doesn't work with boxes with height > width

### ISSUE THREAD

**Issue by hombit** [cds-astro/mocpy#160]
It looks like `mocpy` assumes instances `RectangleSkyRegion` to have height smaller than width, so this code fails with `ValueError: Semi-minor axis must be in ]0, a[`:

```python
from astropy.coordinates import Angle, SkyCoord
from mocpy import MOC
from regions import RectangleSkyRegion

region = RectangleSkyRegion(center=SkyCoord(0, 0, unit='deg'), width=Angle(1, 'deg'), height=Angle(2, 'deg'))
MOC.from_astropy_regions(region, max_depth=10)
```

**Comment by ManonMarchand** [comment]
Hi and thanks for reporting,
This should be fixed in version 0.16.2 :slightly_smiling_face:
