### ISSUE TITLE
Support regions.Regions

### ISSUE THREAD

**Issue by hombit** [cds-astro/mocpy#163]
Currently `MOC.from_astropy_region` supports individual region objects from `astropy-regions` library, but not a collection of them provided by `regions.Regions`. It would be great to have a performant way to build a single MOC from it

**Comment by ManonMarchand** [comment]
Sure! 

As the list of MOCs is also useful. I think the API would look like

```python
MOC.from_astropy_region(my_regions, single_moc=True)
```

And we could also add the `single_moc` argument in the other multimoc creation methods. What do you think @fxpineau ?

**Comment by ManonMarchand** [comment]
Will do, but a more efficient way will be implemented as an option for `from_cones` (strategy for non-overlapping cones already merged in master, second strategy for overlaping cones will be added later) and `from_boxes`
