### ISSUE TITLE
Switch between small cones and big cones strategy in `from_cones`

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/mocpy#164]
We should think about a strategy to switch between the two algos.

@hombit benchmarked the small cone strategy (from MOC-cli) to be 7x faster for some use cases

TODO before:  benchmark with systematic number of cells per cone variations at different depths to determine optimal switch points

**Comment by fxpineau** [comment]
@ManonMarchand (cc @hombit),
I just added a `from_small_cones` method (returning a single MOC) in the Rust wrapper.
See commit 8ddb6eb3c0321eeab3deb3a1a8fd44abec88a45d.

**Comment by fxpineau** [comment]
(Note that I added a multi-threaded version of `from_small_cones`, to be tested, in moc-lib-rust. See [this commit](https://github.com/cds-astro/cds-moc-rust/commit/5032e6163fd88cb57ba535eca9bff744931cfbb2))

**Comment by ManonMarchand** [comment]
Will be more complete with #174 
We decided that switching automatically would be clumsy, so the choice is for the user. There is a new keyword in `from_cones` and in `from_boxes` that allows to chose between small and large strategy. The small one will usually be faste if the shapes don't overlap.

**Comment by hombit** [comment]
Sounds great, thank you so much!
