### ISSUE TITLE
conda-forge only has up to mocpy 0.14.0

### ISSUE THREAD

**Issue by mcoughlin** [cds-astro/mocpy#177]
Would you consider bringing it up to date with 0.16.0?

**Comment by ManonMarchand** [comment]
@fxpineau  :slightly_smiling_face:

**Comment by ManonMarchand** [comment]
Wait a bit @fxpineau , I'll do a release of v0.17 today with the support of python 3.13 and numpy 2.0 anyway

**Comment by mcoughlin** [comment]
Did this end up converging?

**Comment by fxpineau** [comment]
Yep, conda packages for MOCPy 0.17.0 are being built, see
[this PR](https://github.com/conda-forge/mocpy-feedstock/pull/22) and [this action](https://github.com/conda-forge/mocpy-feedstock/runs/31740511374) that is updating [MOCPy's conda-forge page](https://anaconda.org/conda-forge/mocpy).
