### ISSUE TITLE
inMoc and nearMoc methods from STILTS

### ISSUE THREAD

**Issue by ggreco77** [cds-astro/mocpy#37]
I noted interesting methods from the STILTS VO tool that can be useful in mocpy. They are `InMOC` (Indicates whether a given sky position falls strictly within a given MOC) and `NearMOC` (Indicates whether a given sky position either falls within, or is within a certain distance of the edge of a given MOC). The first one seems interesting in the case of the transient events. More information [here](http://www.star.bris.ac.uk/~mbt/stilts/sun256/sun256.html#uk.ac.starlink.ttools.func.Coverage).

**Comment by bmatthieu3** [comment]
Hey @ggreco77 ,

For the InMOC feature, there is a ``MOC.contains`` method https://cds-astro.github.io/mocpy/stubs/mocpy.MOC.html#mocpy.MOC.contains that does this.

For the NearMOC that is an interesting feature. I think we would need a method that returns the distance of a sky position from a specific HEALPix cell at a given depth. @fxpineau - maybe this is more suited for cdshealpix ? With a method like this, I will then be able to compute the distance between the sky position and all the HEALPix cells contained in the MOC, take the min of these distances and compare it to the distance given by the user.

@ggreco77 - For the moment what you can also do is to increase the area of the MOC thanks to ``add_neighbours`` https://cds-astro.github.io/mocpy/stubs/mocpy.MOC.html#mocpy.MOC.add_neighbours. It will return you a bigger MOC increased by one degree of neighbors at the max depth of the MOC. You can then call ``contains`` on it with a list of sky positions. This method does not ask you for a certain distance, but if you want a bigger threshold you can still increase the MOC several times...

**Comment by fxpineau** [comment]
@ggreco77, cc  @mbtaylor,
I don't know exactly the algorithm used in [nearMoc](http://www.star.bris.ac.uk/~mbt/stilts/sun256/uk.ac.starlink.ttools.func.Coverage.html).
Unless I am missing something, computing the exact distance from a point to an HEALPix cell edge is not trivial (HEALPIx cell edges are not great-circle arcs).
One approximate solution may be to create a MOC from a cone (center = sky position, radius = distance, order = approximation level) and test whether the union with the input MOC is empty or not.
@mbtaylor do you have a different approach?

**Comment by mbtaylor** [comment]
@fxpineau yes, testing the intersection between a cone and the target MOC is exactly what I do.  As you note, the result is approximate, the cone is currently generated like this:
```
Healpix.getNested(mocOrder).newConeComputerApprox(radius).overlappingCells(alpha, delta)
```

**Comment by fxpineau** [comment]
@mbtaylor thank you for your answer (of course it relies on the intersection, not the union: I updated my message). 
The MOC being itself an approximate region, it may indeed be an overkill to use a cone resolution deeper than the MOC resolution.
