### ISSUE TITLE
STMOC from Polygon

### ISSUE THREAD

**Issue by dr-rodriguez** [cds-astro/mocpy#40]
There is an existing method to create MOC from a polygon (MOC.from_polygon). We should have a similar method to do the same with ST-MOC. This would be useful when creating STMOC from sets of footprints, where we only wish to describe the boundaries in both space and time.

**Comment by bmatthieu3** [comment]
Do you have a spatial footprint (a MOC), its center skycoord and rotation for every observations ?

If so we could have a:
from_time_ranges_footprint_moc(center_skycoords, angles, spatial_footprint, time_ranges) with:
* _center_skycoords_ an astropy.skycoord of size N
* _angles_ an astropy.Angle of size N
* _spatial_footprint_ a single mocpy.MOC created from MOC.from_polygon
* _time_ranges_ an astropy.time.Time object of size Nx2

Can this help you ?

**Comment by dr-rodriguez** [comment]
As we discussed in person, issue #41 is probably best in terms of handling how to create ST-MOCs so we should close this one and direct users towards that other workflow.
