### ISSUE TITLE
STMOC from existing MOC

### ISSUE THREAD

**Issue by dr-rodriguez** [cds-astro/mocpy#41]
We should consider having a method to enhance an existing MOC with time information so as to produce with STMOC. The example I have in mind is a set of MOC I've been creating for TESS footprints. I would like to just take my existing MOC and add a time range for it.

**Comment by bmatthieu3** [comment]
@dr-rodriguez  - I like this idea, we could have a method like **from_time_ranges_region** taking a list of spatial MOC and a list of astropy.time ranges.

API idea:
`from_time_ranges_region(mocs, time_ranges)` with _mocs_ a list of N mocpy.MOC and _time_ranges_ a astropy.time.Time object of shape Nx2 (one time range per MOC).

Is it what you are looking for ?

**Comment by dr-rodriguez** [comment]
Yes, that would work. I'd suggest a method name of from_time_ranges_moc to make it clearer just in case in the future you support things like s_region/STC-S.

**Comment by BaptisteCecconi** [comment]
@bmatthieu3 I like this option too !

**Comment by bmatthieu3** [comment]
Hi @dr-rodriguez @AdaNebot @BaptisteCecconi, 
There is a [STMOC.from_spatial_coverages](https://cds-astro.github.io/mocpy/stubs/mocpy.STMOC.html#mocpy.STMOC.from_spatial_coverages) for creating a STMOC with a list of time ranges (2 astropy.time.Time 1D array of the same size) and a list of mocpy.MOC objects (same size). This is not very well tested so it can be buggy.

Thanks for giving me feedbacks if this is working for your applications and if it is good in terms of performance or if it can be enhanced.

**Comment by fxpineau** [comment]
@dr-rodriguez, @BaptisteCecconi 
it seems that the feature has been implemented so I close the issue and let you re-open it in case you find a bug or would like improvements.
