### ISSUE TITLE
STMOC missing attributes _to_json and _to_str

### ISSUE THREAD

**Issue by dr-rodriguez** [cds-astro/mocpy#42]
When attempting to serialize an STMOC, json and str representations are not yet available:
`AttributeError: 'STMOC' object has no attribute '_to_json'`
`AttributeError: 'STMOC' object has no attribute '_to_str'`

**Comment by fxpineau** [comment]
Methods `to_string(self, format)` and `from_string(cls, value, forma')` with `format =  'ascii`' or `format = 'json'` and `value` a `str`,  added on MOC, TMOC and STMOC.
Will be available in v0.9.0
