### ISSUE TITLE
Consider renaming WCS class

### ISSUE THREAD

**Issue by astrofrog** [cds-astro/mocpy#43]
The following file:

https://github.com/cds-astro/mocpy/blob/master/mocpy/moc/plot/wcs.py

defines a ``WCS`` class but this confused me at first in the docs given that the core astropy package also includes a class of the same name. I wonder if it could be renamed in MOCPy since it's just a high-level convenience not a general WCS class? (it could even be a function context manager rather than a class?)

**Comment by bmatthieu3** [comment]
I am +1 for this. As of the v0.8.1, WCS class has been renamed World2ScreenMPL
