### ISSUE TITLE
moving mocpy docs causing sphinx failures

### ISSUE THREAD

**Issue by bsipocz** [cds-astro/mocpy#48]
mocpy docs has been moved from https://mocpy.readthedocs.io/en/latest/ to https://cds-astro.github.io/mocpy/ thus causing docs build failures for astroquery.

I'm fixing it for master, but you might want to double check on github where else was the old url used.

**Comment by tboch** [comment]
@bmatthieu3 : is there a way to setup a 301 redirection from https://mocpy.readthedocs.io/en/latest/ to the new URL? Or at least remove the content from readthedocs and put a page with a link to the new URL.

I'm often confused by reading the old version, out of habit!

**Comment by fxpineau** [comment]
@bsipocz, @tboch 
I checked this and removed the last references from the MOCPy doc (thank you).
Unfortunately, I have the impression that there is no easy way to publish a simple static page -- with a redirection -- on readthedoc. I guess that it is to prevent anyone to publish almost anything. If you are aware of a simple way to do it, please let me know.
