### ISSUE TITLE
Unexplained or internal-only attribute "LARK_PARSER_STR" shown in mocpy.MOC API docs

### ISSUE THREAD

**Issue by lpsinger** [cds-astro/mocpy#51]
See attached screen shot.

![Screen Shot 2020-02-24 at 15 37 18](https://user-images.githubusercontent.com/728407/75189158-9c864480-571b-11ea-9a61-2a2ce1fe0289.png)

**Comment by bmatthieu3** [comment]
Thanks for highlighting this!
This is internal. I use a parser package (Lark https://github.com/lark-parser/lark) for deserializing a string to a MOC (from_str method). This variable stores the grammar expressed in the MOC standard (see 2.3.2) http://ivoa.net/documents/MOC/20191007/REC-MOC-1.1-20191007.pdf

**Comment by fxpineau** [comment]
@lpsinger I transformed the `LARK_PARSER_STR` attribute into a private attribute (`__LARK_PARSER_STR`) so that it will not show up any longer in the doc (it is internal business).
It is ok for you?

**Comment by lpsinger** [comment]
Sounds good.
