### ISSUE TITLE
warnings filter reset to default within package

### ISSUE THREAD

**Issue by marxide** [cds-astro/mocpy#54]
There are several cases where the warnings filter is reset to the default. As far as I can tell, this prohibits a user from using their own warning filters. For example, the following still produces `DeprecationWarning`s

```python
import warnings

moc = MOC()
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    boundaries = moc.get_boundaries()
```

I suspect that the internal use of `warnings.simplefilter("default")` is making the above ineffective. Would it be possible to have these default filters removed? Happy to do so and submit a PR if necessary.

**Comment by fxpineau** [comment]
@marxide
`warnings.simplefilter("default")` removed.
Will be taken into acount in next release.
