### ISSUE TITLE
networkx.connected_component_subgraphs removed

### ISSUE THREAD

**Issue by marxide** [cds-astro/mocpy#55]
The function `networkx.connected_component_subgraphs` has been removed from the latest version of `networkx`.

I think either the version of `networkx` for this package should be pinned to <=2.3, or the calls to the above function should be replaced with the suggested replacement, e.g.

```python
G_subgraphs = (G.subgraph(c).copy() for c in connected_components(G))
```

Happy to submit a PR for this if necessary after some guidance on which would be preferred.

**Comment by marxide** [comment]
Just noticed that the version is pinned in the requirements files, but these are targeted to developers/contributors and not users. I think it should also be pinned in `setup.py`, or better yet, change the subgraph call to the above. It seems to work in my local copy and all tests still pass.

**Comment by astrozot** [comment]
Is there any news regarding this issue? It effectively makes `get_boundaries` method unusable. Thank you!

**Comment by fxpineau** [comment]
`networkx` is now pinned to `>=2.5` (and the code has been updated accordingly).
The issue should thus be fixed now.
