### ISSUE TITLE
Empty MOC has interval set array with wrong shape

### ISSUE THREAD

**Issue by lpsinger** [cds-astro/mocpy#64]
An empty MOC has an interval set with the wrong shape. The shape should be (0, 2), but it is (1, 0).

```pycon
>>> from mocpy import MOC
>>> MOC()._interval_set.nested.shape
(1, 0)
```

**Comment by fxpineau** [comment]
@lpsinger If I am correct, it comes from `np.array([[]], dtype=np.uint64)` which is in MOCPy since at least v0.8.0.
```python
>>> import numpy as np
>>> a = np.array([[]], dtype=np.uint64)
>>> a.shape
(1, 0)
```
I replaced it by `np.zeros((0, 2), dtype=np.uint64)` (to be pushed).

**Comment by fxpineau** [comment]
@lpsinger done. Will be ok in next release.

**Comment by lpsinger** [comment]
Nice! Thanks for the fast turnaround.
