### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [cds-astro/mocpy#66]
Problem
---------
On aarch64, `pip install mocpy` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install mocpy` should download the wheels from PyPI.

@bmatthieu3, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by fxpineau** [comment]
@odidev I am working on it for [cds-healpix-python](https://github.com/cds-astro/cds-healpix-python) which is a MOCPy dependency.
By curiosity, are you using Astropy and/or MOCPy on raspberry pi or something similar?

**Comment by odidev** [comment]
@fxpineau I am not using these. I am just working on providing aarch64 wheel support to benefit aarch64 users.

**Comment by fxpineau** [comment]
@odidev 
Merge request accepted. Aarch64 wheels will be done for the next release.
