### ISSUE TITLE
Buiiding MOC from images located in ant FITS extension

### ISSUE THREAD

**Issue by lmichel** [cds-astro/mocpy#68]
The current API allows to build a MOCs from a set of FITS files located in a given folder:

```Python
MOC.from_fits_images(path_l, max_norder)
```

It is however not possible to use the same convenient method when the images are in a FITS extension. This is a case e.g. when we want to build a MOC from exposure maps which are usually not in the primary extension.
In this case we have to build MOCs for each individual file by using `MOC.from_fits_image(hdu, max_norder, mask=None)` and to merge them. This is a bit boring.

Having a function like this:

```Python
MOC.from_fits_dhu(path_l, hdu, max_norder)
```

Would be very helpful.

**Comment by fxpineau** [comment]
The method now takes as optional parameter the index of the HDU iin FITS files, 
see [this line](https://github.com/cds-astro/mocpy/blob/master/python/mocpy/moc/moc.py#L477):
```python
def from_fits_images(cls, path_l, max_norder, hdu_index=0):
```
