### ISSUE TITLE
Comment on slowness of 'from-skycoords' function

### ISSUE THREAD

**Issue by chbrandt** [cds-astro/mocpy#7]
@tboch you say in a [comment in 'from_coo_list'](
https://github.com/cds-astro/mocpy/blob/f154020aefe11f58929d404ab10dfbd8a335b7f0/mocpy/moc.py#L397) the loop over SkyCoords is "very slow". I didn't check this particular case in details, but I have crossed such issue in the past; may be useful to you.

Itemize operations with SkyCoords arrays are very slow. Performance may be significantly increased by reading the values out from the SkyCoord array (in the desired unit, 'deg' for instance) to a simpler structure (e.g, numpy array (N,2)). And then, even if not vectorizing the "add_position" call, it should perform better.

Thanks.

**Comment by tboch** [comment]
Thanks @chbrandt , that's useful, I'm going to try this change.
