### ISSUE TITLE
Getting the list of pixels

### ISSUE THREAD

**Issue by israelmcmc** [cds-astro/mocpy#72]
I noticed that there is no access method or property to get the underlaying list of pixels, is there? Any reason not to have one? I'm working on a project where I ended up needing this.

Or in other words, why is `_uniq_format()` not a "public" method? Maybe I'm just missing the proper way to access this information, sorry if that's the case.

**Comment by israelmcmc** [comment]
That would be it, thank you! In fact, my current workaround is to simply use `m._uniq_format()` (=`m._interval_set.uniq`). It works for now, but of course it's not a good idea to use these "private" properties as the code could break in future releases.

**Comment by fxpineau** [comment]
MOC now has a `uniq_hpx` method, see [here](https://github.com/cds-astro/mocpy/blob/master/python/mocpy/moc/moc.py#L1411).

WARNING: v0.12 contains a few breaking changes, see the CHANGELOG file
