### ISSUE TITLE
Plotiing a MOC without giving a center.

### ISSUE THREAD

**Issue by lmichel** [cds-astro/mocpy#73]
Plotting MOCs as shown in the doc examples is a great feature very helpful for e.g. tuning MOC generation.
This unfortunately requires the user to set by hand the projection center.  
This plotting feature would be quite more convenient whether that center was computed automatically from the MOC itself.

The code snippet below, derived from the [doc](https://cds-astro.github.io/mocpy/examples/examples.html), shows how such feature could be implemented
  
```python
from mocpy import MOC, World2ScreenMPL
from astropy.coordinates import Angle, SkyCoord
import astropy.units as u
# Load a MOC
filename = './../../resources/P-SDSS9-r.fits'
moc = MOC.from_fits(filename)
# Plot the MOC using matplotlib
import matplotlib.pyplot as plt
fig = plt.figure(111, figsize=(15, 10))
# Define a astropy WCS easily
with World2ScreenMPL(fig, 
        fov=200 * u.deg,
        #center=SkyCoord(0, 20, unit='deg', frame='icrs'),
        center=moc.center(unit='deg', frame='icrs'), ## <<< Proposal
        coordsys="icrs",
        rotation=Angle(0, u.degree),
        projection="AIT") as wcs:
    ax = fig.add_subplot(1, 1, 1, projection=wcs)
    # Call fill with a matplotlib axe and the `~astropy.wcs.WCS` wcs object.
    moc.fill(ax=ax, wcs=wcs, alpha=0.5, fill=True, color="green")
    moc.border(ax=ax, wcs=wcs, alpha=0.5, color="black")
plt.xlabel('ra')
plt.ylabel('dec')
plt.title('Coverage of P-SDSS9-r')
plt.grid(color="black", linestyle="dotted")
plt.show()
```

**Comment by bmatthieu3** [comment]
@fxpineau - is something like could work a little ?
* getting the external (or internal) cells border at maximum depth of the moc
* the center is the average of the center of these cells
* we should test if this computed center lies in the moc. If not, we take as center the opposite of that vector (case of a moc coverage more than half the sphere)

I am not sure at all this is a general case that work for every possible moc but it may be a good start. For example, a moc containing 2 non connected region that are in the opposite direction on the sphere could result in a center that is between the 2 regions and not in any of these 2 mocs, but rather equidistant from them.

**Comment by lmichel** [comment]
User comment: 
If you take a sparse MOC e.g. XMM spread out over the sky by with 4% of coverage, your method is likely to fall back in a non covered area.
A work around could :
- computing the center as you did but without caring about the half sphere
- Finding in the closest  MOC cell of the center and taking it as MOC center
- Computing the max  cell distances (from both width and height ) from that actual center to get the display size.

With this method

**Comment by fxpineau** [comment]
Implemented in the [MOC.wcs](https://github.com/cds-astro/mocpy/blob/master/python/mocpy/moc/moc.py#L1199) method , relying on the new methods:
* [barycenter](https://github.com/cds-astro/mocpy/blob/master/python/mocpy/moc/moc.py#L1443)
* [largest_distance_from_coo_to_vertices](https://github.com/cds-astro/mocpy/blob/master/python/mocpy/moc/moc.py#L1448)
