### ISSUE TITLE
Add in the contributing section of the doc a tuto to run the notebooks locally

### ISSUE THREAD

**Issue by bmatthieu3** [cds-astro/mocpy#85]
Refers to the cmds found in the notebook ci. This may encourage contributors to also test the notebooks

**Comment by ManonMarchand** [comment]
You mean we should do that for release 0.12.0 ?

**Comment by bmatthieu3** [comment]
no, it is just an idea that was passing through my head so I opened this issue, so for later of course

**Comment by ManonMarchand** [comment]
done :)
