### ISSUE TITLE
Make _store_index a read-only property

### ISSUE THREAD

**Issue by bmatthieu3** [cds-astro/mocpy#89]
So that it cannot be manually set by any users:

https://stackoverflow.com/questions/14594120/when-should-an-attribute-be-private-and-made-a-read-only-property

**Comment by fxpineau** [comment]
If it can be accessed by sub-classes, yes!
@ManonMarchand also mentioned that `AbstractClass.store_index_dtype` should be private (or at least protected)
and if it can be replace by a static variable it would be even nicer :)
